pipelines:
  default:
    - step:
        name: Push docker image to the Heroku
        deployment: Production
        services:
          - docker
        script:
          - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          - heroku container:login
          - heroku container:push web -a $HEROKU_APP_NAME
          - heroku container:release web -a $HEROKU_APP_NAME